from _typeshed import Incomplete

class StateStorageBase:
    def __init__(self) -> None: ...
    async def set_data(self, chat_id, user_id, key, value) -> None: ...
    async def get_data(self, chat_id, user_id) -> None: ...
    async def set_state(self, chat_id, user_id, state) -> None: ...
    async def delete_state(self, chat_id, user_id) -> None: ...
    async def reset_data(self, chat_id, user_id) -> None: ...
    async def get_state(self, chat_id, user_id) -> None: ...
    async def save(self, chat_id, user_id, data) -> None: ...

class StateContext:
    obj: Incomplete
    data: Incomplete
    chat_id: Incomplete
    user_id: Incomplete
    def __init__(self, obj, chat_id, user_id) -> None: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc_val, exc_tb): ...
