from _typeshed import Incomplete
from telebot.asyncio_storage.base_storage import StateContext as StateContext, StateStorageBase as StateStorageBase

class StateMemoryStorage(StateStorageBase):
    data: Incomplete
    def __init__(self) -> None: ...
    async def set_state(self, chat_id, user_id, state): ...
    async def delete_state(self, chat_id, user_id): ...
    async def get_state(self, chat_id, user_id): ...
    async def get_data(self, chat_id, user_id): ...
    async def reset_data(self, chat_id, user_id): ...
    async def set_data(self, chat_id, user_id, key, value): ...
    def get_interactive_data(self, chat_id, user_id): ...
    async def save(self, chat_id, user_id, data) -> None: ...
