from _typeshed import Incomplete
from telebot.asyncio_storage.base_storage import StateContext as StateContext, StateStorageBase as StateStorageBase

redis_installed: bool
is_actual_aioredis: bool

class StateRedisStorage(StateStorageBase):
    redis: Incomplete
    prefix: Incomplete
    def __init__(self, host: str = 'localhost', port: int = 6379, db: int = 0, password: Incomplete | None = None, prefix: str = 'telebot_', redis_url: Incomplete | None = None) -> None: ...
    async def get_record(self, key): ...
    async def set_record(self, key, value): ...
    async def delete_record(self, key): ...
    async def set_state(self, chat_id, user_id, state): ...
    async def delete_state(self, chat_id, user_id): ...
    async def get_value(self, chat_id, user_id, key): ...
    async def get_state(self, chat_id, user_id): ...
    async def get_data(self, chat_id, user_id): ...
    async def reset_data(self, chat_id, user_id): ...
    async def set_data(self, chat_id, user_id, key, value): ...
    def get_interactive_data(self, chat_id, user_id): ...
    async def save(self, chat_id, user_id, data): ...
