# Standard Library
from types import TracebackType

# Third Party Stuff
from _typeshed import Incomplete

class StateStorageBase:
    def __init__(self) -> None: ...
    def set_data(self, chat_id, user_id, key, value) -> None: ...
    def get_data(self, chat_id, user_id) -> None: ...
    def set_state(self, chat_id, user_id, state) -> None: ...
    def delete_state(self, chat_id, user_id) -> None: ...
    def reset_data(self, chat_id, user_id) -> None: ...
    def get_state(self, chat_id, user_id) -> None: ...
    def get_interactive_data(self, chat_id, user_id) -> None: ...
    def save(self, chat_id, user_id, data) -> None: ...

class StateContext:
    obj: Incomplete
    data: Incomplete
    chat_id: Incomplete
    user_id: Incomplete
    def __init__(self, obj, chat_id, user_id) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None): ...
