from _typeshed import Incomplete
from telebot.storage.base_storage import StateContext as StateContext, StateStorageBase as StateStorageBase

class StateMemoryStorage(StateStorageBase):
    data: Incomplete
    def __init__(self) -> None: ...
    def set_state(self, chat_id, user_id, state): ...
    def delete_state(self, chat_id, user_id): ...
    def get_state(self, chat_id, user_id): ...
    def get_data(self, chat_id, user_id): ...
    def reset_data(self, chat_id, user_id): ...
    def set_data(self, chat_id, user_id, key, value): ...
    def get_interactive_data(self, chat_id, user_id): ...
    def save(self, chat_id, user_id, data) -> None: ...
