def format_text(*args, separator: str = '\n'): ...
def escape_html(content: str) -> str: ...
def escape_markdown(content: str) -> str: ...
def mbold(content: str, escape: bool | None = True) -> str: ...
def hbold(content: str, escape: bool | None = True) -> str: ...
def mitalic(content: str, escape: bool | None = True) -> str: ...
def hitalic(content: str, escape: bool | None = True) -> str: ...
def munderline(content: str, escape: bool | None = True) -> str: ...
def hunderline(content: str, escape: bool | None = True) -> str: ...
def mstrikethrough(content: str, escape: bool | None = True) -> str: ...
def hstrikethrough(content: str, escape: bool | None = True) -> str: ...
def mspoiler(content: str, escape: bool | None = True) -> str: ...
def hspoiler(content: str, escape: bool | None = True) -> str: ...
def mlink(content: str, url: str, escape: bool | None = True) -> str: ...
def hlink(content: str, url: str, escape: bool | None = True) -> str: ...
def mcode(content: str, language: str = '', escape: bool | None = True) -> str: ...
def hcode(content: str, escape: bool | None = True) -> str: ...
def hpre(content: str, escape: bool | None = True, language: str = '') -> str: ...
def hide_link(url: str) -> str: ...
def mcite(content: str, escape: bool | None = True) -> str: ...
def hcite(content: str, escape: bool | None = True) -> str: ...
def apply_html_entities(text: str, entities: list | None, custom_subs: dict[str, str] | None) -> str: ...
