from _typeshed import Incomplete
from collections.abc import Generator

pil_imported: bool

def is_string(var) -> bool: ...
def is_dict(var) -> bool: ...
def is_bytes(var) -> bool: ...
def is_pil_image(var) -> bool: ...
def pil_image_to_file(image, extension: str = 'JPEG', quality: str = 'web_low'): ...
def chunks(lst, n) -> Generator[Incomplete, None, None]: ...
def generate_random_token() -> str: ...
